---
- name: Deploy image from nexus repo
  hosts: all
  tasks:
    - name: login to nexus
      docker_login:
        registry_url: 13.68.144.25:8085
        username: admin
        password: admin@123
        reauthorize: true
    - name: Run docker container
      docker_container:
        name: chatapp
        image: 13.68.144.25:8085/chatapp
        state: started
        pull: true
        ports: 
         - "8082:8080"
    - name: Connect to server on port 8082 and check status
      tags: test
      uri:
        url: http://localhost:8082
      register: result
      until: "result.status ==200"
      retries: 5
      delay: 10